name: Deploy Project

on:
  push:
    branches:
      - production  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up SSH key for authentication
    - name: Set up SSH key for authentication
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} # The private SSH key stored in GitHub secrets

    # Step 3: Deploy to the server via SSH
    - name: Deploy to server via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          # Navigate to the project directory
          cd /mnt/data/Digital_Hub
          
          # Pull the latest changes from GitHub
          git pull origin production
          
          # Activate virtual environment 
          source .venv/bin/activate  

          # Navigate to the 'core' directory (where your migrations are located)
          cd core

          poetry install --no-root
          
          # Run migrations
          poetry run python manage.py makemigrations
          
          # Run migrations
          poetry run python manage.py migrate
          
          # Collect static files
          poetry run python manage.py collectstatic --noinput
            
          # Restart the uWSGI service
          sudo systemctl restart uwsgi.service

          # Restart the Nginx service
          sudo systemctl restart nginx.service

          # Restart the celery service
          sudo systemctl restart celery.service

        EOF
